import {
  ArrowDownIcon,
  ArrowDownLeftIcon,
  ArrowDownRightIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowUpLeftIcon,
  ArrowUpRightIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  CheckboxCheckFillIcon,
  CheckboxCheckIcon,
  CheckboxMultiCheckFillIcon,
  CheckboxMultiCheckIcon,
  CheckboxUncheckIcon,
  FilterIcon,
  FilterRemoveIcon,
  FilterResetIcon,
  HashtagIcon,
  HouseIcon,
  ImageIcon,
  LoginIcon,
  LogoutIcon,
  NoImageIcon,
  RadioCheckedIcon,
  RadioUncheckedIcon,
  SettingsGearIcon,
  StatusErrorIcon,
  StatusHelpIcon,
  StatusInfoIcon,
  StatusMisuseIcon,
  StatusSuccessIcon,
  StatusWarningIcon,
  StatusErrorOutlineIcon,
  StatusHelpOutlineIcon,
  StatusInfoOutlineIcon,
  StatusMisuseOutlineIcon,
  StatusSuccessOutlineIcon,
  UserFillIcon,
  UserIcon,
  ViewFillIcon,
  ViewIcon,
  ViewOffFillIcon,
  ViewOffIcon,
  CloseIcon,
  CloseIconFill,
  CloseIconOutline,
} from ".";

export const iconLookup = {
  ArrowDown: <ArrowDownIcon />,
  ArrowDownLeft: <ArrowDownLeftIcon />,
  ArrowDownRight: <ArrowDownRightIcon />,
  ArrowLeft: <ArrowLeftIcon />,
  ArrowRight: <ArrowRightIcon />,
  ArrowUp: <ArrowUpIcon />,
  ArrowUpLeft: <ArrowUpLeftIcon />,
  ArrowUpRight: <ArrowUpRightIcon />,
  CaretDown: <CaretDownIcon />,
  CaretLeft: <CaretLeftIcon />,
  CaretRight: <CaretRightIcon />,
  CaretUp: <CaretUpIcon />,
  CheckboxCheck: <CheckboxCheckIcon />,
  CheckboxCheckFill: <CheckboxCheckFillIcon />,
  CheckboxMultiCheck: <CheckboxMultiCheckIcon />,
  CheckboxMultiCheckFill: <CheckboxMultiCheckFillIcon />,
  CheckboxUncheck: <CheckboxUncheckIcon />,
  Close: <CloseIcon />,
  CloseFill: <CloseIconFill />,
  CloseOutline: <CloseIconOutline />,
  Filter: <FilterIcon />,
  FilterRemove: <FilterRemoveIcon />,
  FilterReset: <FilterResetIcon />,
  Hashtag: <HashtagIcon />,
  House: <HouseIcon />,
  Image: <ImageIcon />,
  NoImage: <NoImageIcon />,
  Login: <LoginIcon />,
  Logout: <LogoutIcon />,
  RadioChecked: <RadioCheckedIcon />,
  RadioUnchecked: <RadioUncheckedIcon />,
  Settings: <SettingsGearIcon />,
  StatusError: <StatusErrorIcon />,
  StatusHelp: <StatusHelpIcon />,
  StatusInfo: <StatusInfoIcon />,
  StatusMisuse: <StatusMisuseIcon />,
  StatusSuccess: <StatusSuccessIcon />,
  StatusWarning: <StatusWarningIcon />,
  StatusErrorOutline: <StatusErrorOutlineIcon />,
  StatusHelpOutline: <StatusHelpOutlineIcon />,
  StatusInfoOutline: <StatusInfoOutlineIcon />,
  StatusMisuseOutline: <StatusMisuseOutlineIcon />,
  StatusSuccessOutline: <StatusSuccessOutlineIcon />,
  UserFill: <UserFillIcon />,
  User: <UserIcon />,
  ViewFill: <ViewFillIcon />,
  View: <ViewIcon />,
  ViewOffFill: <ViewOffFillIcon />,
  ViewOff: <ViewOffIcon />,
};

export type IconType = keyof typeof iconLookup;

export default function Icon({ name }: { name?: IconType }) {
  if (!name) return null;
  return iconLookup[name ?? "ArrowRight"];
}
